import { useState, useEffect } from "react";
import { toast } from "react-toastify";
import PropTypes from "prop-types";

import UserStore from "../../../stores/UserStore";

const API = import.meta.env.VITE_API_URL;

const EditMatrimonyUser = ({ matrimonyUser, setView }) => {
  const [formData, setFormData] = useState({
    firstName: matrimonyUser.firstName,
    lastName: matrimonyUser.lastName,
    email: matrimonyUser.email,
    password: "",
    phone: matrimonyUser.phone,
    gender: matrimonyUser.gender,
    dob: matrimonyUser.dob,
    timeOfBirth: matrimonyUser.timeOfBirth,
    placeOfBirth: matrimonyUser.placeOfBirth,
    community: matrimonyUser.community,
    religion: matrimonyUser.religion,
    caste: matrimonyUser.caste,
    subCaste: matrimonyUser.subCaste,
    motherTongue: matrimonyUser.motherTongue,
    country: matrimonyUser.country,
    state: matrimonyUser.state,
    city: matrimonyUser.city,
    address: matrimonyUser.address,
    pincode: matrimonyUser.pincode,
    maritalStatus: matrimonyUser.maritalStatus,
    haveChildren: matrimonyUser.haveChildren,
    noOfChildren: matrimonyUser.noOfChildren,
    height: matrimonyUser.height,
    weight: matrimonyUser.weight,
    complexion: matrimonyUser.complexion,
    bodyType: matrimonyUser.bodyType,
    bloodGroup: matrimonyUser.bloodGroup,
    donateBlood: matrimonyUser.donateBlood,
    qualification: matrimonyUser.qualification,
    educationSpecialization: matrimonyUser.educationSpecialization,
    currentLocation: matrimonyUser.currentLocation,
    immigrationStatus: matrimonyUser.immigrationStatus,
    designation: matrimonyUser.designation,
    designationDetails: matrimonyUser.designationDetails,
    annualIncome: matrimonyUser.annualIncome,
    fatherName: matrimonyUser.fatherName,
    fatherOccupation: matrimonyUser.fatherOccupation,
    fatherMobile: matrimonyUser.fatherMobile,
    motherName: matrimonyUser.motherName,
    motherOccupation: matrimonyUser.motherOccupation,
    motherMobile: matrimonyUser.motherMobile,
    grandfatherName: matrimonyUser.grandfatherName,
    grandmotherName: matrimonyUser.grandmotherName,
    nanaName: matrimonyUser.nanaName,
    naniName: matrimonyUser.naniName,
    noOfBrothers: matrimonyUser.noOfBrothers,
    noOfSisters: matrimonyUser.noOfSisters,
    believeInHoroscope: matrimonyUser.believeInHoroscope,
    rashi: matrimonyUser.rashi,
    gotra: matrimonyUser.gotra,
    varna: matrimonyUser.varna,
    mangalShani: matrimonyUser.mangalShani,
    diet: matrimonyUser.diet,
    smoke: matrimonyUser.smoke,
    drink: matrimonyUser.drink,
    hobbies: matrimonyUser.hobbies,
    ageGap: matrimonyUser.ageGap,
    partnerReligion: matrimonyUser.partnerReligion,
    partnerCaste: matrimonyUser.partnerCaste,
    partnerSubCaste: matrimonyUser.partnerSubCaste,
    partnerQualification: matrimonyUser.partnerQualification,
    partnerOccupation: matrimonyUser.partnerOccupation,
    partnerAnnualIncome: matrimonyUser.partnerAnnualIncome,
    mangalik: matrimonyUser.mangalik,
    partnerMaritalStatus: matrimonyUser.partnerMaritalStatus,
    goAbroad: matrimonyUser.goAbroad,
    disability: matrimonyUser.disability,
    disabilityPercentage: matrimonyUser.disabilityPercentage,
    about: matrimonyUser.about,
  });

  return <div>EditMatrimonyUser</div>;
};

export default EditMatrimonyUser;
